version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CloudfrontLambdaAtEdge"
s3_bucket = "aws-sam-cli-dgallagher"
s3_prefix = "CloudfrontLambdaAtEdge"
region = "us-east-1"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM, CAPABILITY_IAM, CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Stage=\"dev\" LogLevel=\"warn\" ModifyOriginLambdaFunctionVersion=\"1\" CustomMetricsLambdaFunctionVersion=\"2\" PerformRedirectLambdaName=\"PerformRedirectLambda\""

